### ISSUE TITLE
Subversions for master branch

### ISSUE THREAD

**Issue by ksahlin** [ksahlin/StrobeAlign#106]
I realised that now that we want to compare possibly multiple versions of strobealign. It would be good if we have a versioning number so that it is clear which version is installed. Not sure what the best solution is.

One suggestion: since we work with pull requests (well, I should start with it too..), how about labelling the version to be pushed to master with the current stable version-id plus the github 7-characters ID on the last commit before the merge?  So:

```

$ strobealign-0.7.1
  strobealign reference [reads1] [reads2] {OPTIONS}

    StrobeAlign 0.7.1

  OPTIONS: ...
```  

```

$ strobealign-master
  strobealign reference [reads1] [reads2] {OPTIONS}

    StrobeAlign 0.7.1-2039d7da

  OPTIONS: ...
```

**Comment by marcelm** [comment]
We can possibly use https://github.com/andrew-hardin/cmake-git-version-tracking for this.
