### ISSUE TITLE
Make -r mandatory when -i (indexing only)?

### ISSUE THREAD

**Issue by ksahlin** [ksahlin/strobealign#109]
This is more of a failsafe. I just realised that indexing will run with default parameters when read files not given. That is
```
strobealign -i idx_path ref
strobealign idx_path reads1 reads2
```

will index with default params (150bp reads i think?) even though reads may be shorter or longer. 

Related: function `estimate_read_length` estimates read length when at least one read file is given, but what happens when `strobealign -i idx_path ref` is run? I is not clear as parameters are not printed to output.

**Comment by marcelm** [comment]
I think we should describe what the use cases for separate index creation are. Some could be:

1. A user wants to map many small Illumina libraries with similar read length against the human genome and save time by pre-computing the index.
2. A cluster admin wants to provide a couple of genomes to their users along with pre-computed indices.

It’s an added challenge that the index is read-length specific. For case 1, the user needs to be aware that the index they created is only usable for those libraries that have roughly the same read length. For case 2, the admin would need to create multiple indices for different read lengths.

In any case, we need to clearly communicate that an index is read-length specific. Perhaps one way to do this is to include the read length in the index file name. As your issue title implies, we should probably focus on the read length as the main criterion. The `IndexParameters::from_read_length` function has six different indexing presets depending on the read length, so these could be the six different index variants that are possible.

So perhaps something like `GRCh38.sti175` would be the index for the "read_length<=175" preset. That makes it possible to have multiple indices next to each other.

If someone wants to deviate from the presets (override k, s, l, u, etc.), we could require that they do not use a pre-computed index (or they get a file name without the read length in it).

**Comment by ksahlin** [comment]
I agree with your proposal and have made a suggestion based on what you write here in #115. I think it takes care of making it clear that index is read length specific.
