### ISSUE TITLE
CMake compilation supported?

### ISSUE THREAD

**Issue by sjaenick** [ksahlin/StrobeAlign#11]
Hi there,

tried to compile v0.4 (on Ubuntu) from source via cmake, but - https://github.com/ksahlin/StrobeAlign/blob/main/CMakeLists.txt#L6 refers to `source/edlib.cpp source/edlib.h` which are not present in the repository/release tarball.

Compiling via `g++ -std=c++14 main.cpp source/index.cpp source/xxhash.c source/ksw2_extz2_sse.c source/ssw_cpp.cpp source/ssw.c -lz -fopenmp -o strobealign -O3 -mavx2`, as outlined in the README, works as intended, though.

Also, could you consider lowering `cmake_minimum_required`? 3.19 isn't widely deployed, Ubuntu 20.04 LTS currently ships
with 3.16.3, for example.

Thanks a lot!

**Comment by ksahlin** [comment]
Hi @sjaenick ,

I will release v0.5 later today or tomorrow.  I will fix this issue at the same time. 

Strobealign v0.5 comes with many improvements for variant calling. For SNV and INDEL calling I would wait to install 0.5. v0.4 is still good for coverage mapping etc. 

Will get back to this issue soon.

Best,
K

**Comment by sjaenick** [comment]
Thanks a lot! Also, that's a pretty fast reply - very much appreciated!

**Comment by ksahlin** [comment]
Hi @sjaenick,

I have now updated the Cmake file and released v0.5. I would be interested in any form of feedback.

Best,
Kristoffer
