### ISSUE TITLE
Suggestions for the on-disk index

### ISSUE THREAD

**Issue by marcelm** [ksahlin/strobealign#115]
Now with a little bit of experience of using the on-disk index, I would like to suggest a couple of changes in the way the on-disk index is handled (considering the discussions in, for example, #111 and #109).

* [x] If `-i` is provided, do not compute alignments (reported in #108), only create the index and store it to disk. Possibly complain if read files are provided.
* [x] Let option `-i` not accept a path, and instead always write the index to a file named as the FASTA file plus `.sti` (example: the index for `phix.fasta` is written to `phix.fasta.sti`). This ensures that the correct extension is used.
* [x] Add an option that means "a pre-computed index exists, use it". The name of the index file is reconstructed from the FASTA file name by adding `.sti`.
* [x] Do not store the sequences in the index file. With the above, the name of the FASTA file is also available and reading it is quite cheap. (If we want to be fancy, we could store a checksum to ensure the contents of the FASTA file haven’t changed.)
* [x] Store the index parameters in the index file.
* [x] When mapping with a pre-computed index, load the index parameters from the index file (and complain if any are provided on the command line).

**Comment by ksahlin** [comment]
I agree with all of the above. But how to make the most minimal user interface?

One idea: How about requiring `-i` to take a parameter for the read length then (i.e., dictating all indexing params). This will prevent the indexing to take two mandatory parameters complicating the interface further.

A proposition:

```
# Creates index ref.fa.stiX, -i needs a read length X to decide indexing parameters
strobealign -i X ref.fa

# Use previously created index refs.fa.stiX to align
# complain if inferred read params X' and indexed X (from ref.fa.stiX) differ                
strobealign -P ref.fa reads1.fq reads2.fq  

# Create index and align accepts any params and inferred read length
strobealign ref.fa reads1.fq reads2.fq     
```

**Comment by marcelm** [comment]
I started work on this in #117 as you may have seen. I called the option `--use-index`, but we can add `-P` as an alias.

I’m not so sure about making `-i` require the read length as a parameter because it is a little bit inconsistent to use `-r` for the read length in one case and `-i` in another. Also, thinking about the above points, I realized it is more practical to allow providing a read file when creating the index. The reads are then only used to estimate the read length. The user doesn’t have to find out the read length themselves. So you would have these variants:
```
strobealign -i ref.fasta reads.1.fastq reads.2.fastq  # Use read length from the FASTQ files
strobealign -i -r 150 -r ref.fasta  # Use explicitly provided read length
```

BTW, I still think that subcommands would be the way to go (#59). If we want to do to the above properly, then we should not allow any other option together with `-i` except `-r`, and this error checking is hard to do without subcommands. (I think there is some way to do it with mutually exclusive groups in the command-line parsing library that we use, but I’m quite sure it’ll quickly become a mess).

**Comment by marcelm** [comment]
All of the above has been implemented, so I think this issue can be closed. We can have the subcommands discussion in #59.
