### ISSUE TITLE
Run regular tests on a non-toy dataset

### ISSUE THREAD

**Issue by marcelm** [ksahlin/StrobeAlign#128]
To avoid issues like the one fixed by #127, we need more extensive tests that cover more cases. It appears some issues are only found by using a larger reference, so that is what we should test. The smallest reference I have tried (*D. melanogaster*) has 130 Mbp, which takes to long to process be run as part of CI. So for the moment, I would just add a script that needs to be run manually. 

Perhaps we can also find a dataset with a reference size between phiX and *D. melanogaster* that is faster to process and still exhibits the problem from #127.

**Comment by ksahlin** [comment]
How about a small repetitive genome? Perhaps even a simulated genome and reads. I could generate a small (10Mb repetitive genome) and 100k reads it it would be good.

**Comment by marcelm** [comment]
That sounds good! Can you try to generate one with 1 Mbp as well?

**Comment by ksahlin** [comment]
@marcelm @PaulPyl 

Simulated 1Mbp test instance has been shared with you over box (you should have received an invite). The instance is created as follows:

```
# generate genome of roughly 1Mbp with 50 concatenated 20k repeat copies with 5% SNP rate, 0.01% indel rate (1-1000bp)
python alignment_evaluation/evaluation_contigs/generate_similar_seqs.py 50 20000 0.05 0.0001 sim_test_genome.fa

# Create a related genome with the given mutation rates below (e.g., 0.5% SNP rate)
mason_variator --sv-indel-rate 0.00005 --snp-rate 0.005 --small-indel-rate 0.0005 \
               --max-small-indel-size 50 -ir sim_test_genome.fa -ov sim_test_genome_variants.vcf

# Reads are now simulated from related genome, 2*150bp Illumina
mason_simulator -ir sim_test_genome.fa -n 100000 -iv sim_test_genome_variants.vcf --illumina-read-length 150 \
                -o reads_L.fq -or reads_R.fq -oa truth.sam

# Run strobealing current release v0.7.1
strobealign-v0.7.1  sim_test_genome.fa  reads_L.fq reads_R.fq > strobealign_v0.7.1.sam
```
