### ISSUE TITLE
Output change by rescue_read refactor

### ISSUE THREAD

**Issue by marcelm** [ksahlin/StrobeAlign#139]
Commit 13bdc5d introduced a `rescue_read` function that is used for the cases that either read 1 or read 2 need to be rescued.

The refactoring changes the output in some cases (but not the accuracy) for the following reason. Previously, there was this function call for both cases (rescue read 1 or rescue read 2): `get_best_scoring_pair(aln_scores1, aln_scores2, ...)` In both cases, read 1 was the first argument and read 2 the second. With the refactoring, the role of read 1 and 2 is reversed in one of the cases. If there are multiple best scoring pairs, it appears that the sort then gives different results:
https://github.com/ksahlin/StrobeAlign/blob/e758839978c3df013bccae22ec70b695d7062c49/src/aln.cpp#L1477

The function is otherwise symmetric so that it doesn’t matter which read is 1 and which is 2, so I would tend to leave this as it is (also because accuracy does not change, only how ties are broken), but I wanted to mention it.

**Comment by marcelm** [comment]
Ok, since @ksahlin gave me a :+1:, I’ll close this without taking any further action.

**Comment by ksahlin** [comment]
Yeah I am not sure I have a good suggestion. Seems okay to ignore for now though? 

I have just set off an evaluation of latest master (commit 464a852), let's see. I am currently only benchmarking index-and-align mode. I will then include also the 'first index, then alignment' option run (with this https://github.com/ksahlin/StrobeAlign/pull/134), but looking at the two separate modes and runtime difference is not the priority right now.
