### ISSUE TITLE
Accuracy regressions since v0.7.1

### ISSUE THREAD

**Issue by marcelm** [ksahlin/StrobeAlign#140]
This is to document which accuracy changes I found since v0.7.1.

## Test data

Only paired-end reads.
* simulated Drosophila
  - Queries: First 1 million 50 bp reads from /proj/snic2022-6-31/nobackup/strobemap_eval/reads_PE/drosophila/
  - Reference: /proj/snic2022-6-31/nobackup/strobemap_eval/genomes/drosophila.fa
* real Drosophila
  - Queries: First 1 million reads of SRR6055476
  - Reference: [GCF_000001215.4](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/215/GCF_000001215.4_Release_6_plus_ISO1_MT/GCF_000001215.4_Release_6_plus_ISO1_MT_genomic.fna.gz)
* CHM13
  - Queries: First 100'000 reads of /proj/snic2022-6-31/nobackup/strobemap_eval/reads_PE/CHM13/200_?.fq
  - Reference: /proj/snic2022-6-31/nobackup/strobemap_eval/genomes/CHM13.fa

Command used: `strobealign-${commithash} -t 1 ${reference} ${r1} ${r2} | samtools view --no-PG -o out.bam`

## Commits with accuracy or other output changes

|Commit|Accuracy in CHM13|Description|Fix/discussion|Trigger in real Drosophila|
|-|-|-|-|-|
|v0.7.1|94.3725||baseline||
|cd46f8f|94.363|Use std::{max,min,abs} instead of ternary operators|#136|SRR6055476.524|
|14d512f|94.3650|Fix a probable logic error due to a typo|||
|d987274|94.169|Do not convert reference to uppercase in seq_to_randstrobes2|#138|?|
|13bdc5d|94.169|Factor out rescue_read|#139|SRR6055476.15|
|6973009|92.875|Invert conditions to allow early break|#127|?|
|d82ce31|93.997|Bug in only this one commit: `filter_cutoff` was set incorrectly|||
|720887d|92.876|Fix incorrect refactor, part 1|||
|8d512a9|94.169|Fix incorrect refactor, part 2|||
|e758839|94.1765|Merge pull request #136 from ksahlin/fix-max||
|464a852|94.3745|Merge pull request https://github.com/ksahlin/StrobeAlign/pull/138 from ksahlin/uppercase||

**Comment by ksahlin** [comment]
This is just.. world class detective work.. I am so impressed.

Is it correctly interpreted that the accuracy column simply lists the accuracy produced with the given commit? That is, ignoring other bugs that might be present in the commits.

**Comment by marcelm** [comment]
Thanks! I don’t feel so happy about introducing those changes, though. I’ll add tests on larger datasets before doing any more refactoring.

The table lists commits where either the accuracy changed or something else happened. The accuracy was unchanged for the intervening commits. For example, from cd46f8f to the commit immediately preceding 14d512f, the accuracy was 94.363. (Except for the row with d82ce31, which shows the accuracy of only a single commit. Accuracy was 92.875 before and after.)

I will update the table with the most recent merged PRs.

**Comment by ksahlin** [comment]
I see, really neat!

**Comment by marcelm** [comment]
I’ve gone through the BAM files themselves (only for the real Drosophila dataset) and found only one extra commit that inadvertenty introduced a change. It is 5b462d6. Here is the diff of the alignments (- is before, + is after) for the first of two affected read pairs in the simulated Drosophila dataset (CHM13 was not affected):
```
-simulated.262476/1 97  211000022278483 515 60  2S48=   3L  14468499    14468024    TGGAAATTAAATTTTTTGGCATTATTTTGCAAATTTTGATGACCCCCCTC  HIHHGGIHHDHHFFIGIHIDIIHIEFG>IGEIFDIEHIBIG;I7>II5I@    NM:i:0  AS:i:96
+simulated.262476/1 65  211000022278483 515 60  2S48=   211000022278398 443 -122    TGGAAATTAAATTTTTTGGCATTATTTTGCAAATTTTGATGACCCCCCTC  HIHHGGIHHDHHFFIGIHIDIIHIEFG>IGEIFDIEHIBIG;I7>II5I@    NM:i:0  AS:i:96

-simulated.262476/2 145 3L              14468499  60  9S10=1X30=  211000022278483 515 -14468024   ATATGGAATGTGTTGGAATNTACTATTCAACCTACAAAAATAACGTTAAA  HIII7CIIIFIIIEIFIIGIHIB8IIIIIIBIIFIIFIEGIGHIIIGHIH    NM:i:1  AS:i:72
+simulated.262476/2 129 211000022278398      443  60  30=1X9=10S  211000022278483 515       122   TTTAACGTTATTTTTGTAGGTTGAATAGTANATTCCAACACATTCCATAT  HIHGIIIHGIGEIFIIFIIBIIIIII8BIHIGIIFIEIIIFIIIC7IIIH    NM:i:1  AS:i:70
```
I have no idea at the moment why such a change occurs. It appears that the `robin_hood::unordered_map` behaves differently when it is cleared and then re-filled compared to creating a new one from scratch.

I’m inclined to just leave this as it is, considering also that the new result makes more sense (both reads mapped close to each other on the same contig).

**Comment by ksahlin** [comment]
My interpretation/guess: The two different versions produce alignment with the same PE-score, which is the sum of the individual read alignment scores, as none of the alignment combinations are properly paired (which would give them a joint score). 

So the robin hood map maybe introduces an ordering difference in sort scores, which causes the versions to pick different?

**Comment by marcelm** [comment]
Finally, everything is fixed! PR #138 brought us over the line and accuracy is now very slightly higher than in v0.7.1 (see updated table).

> The two different versions produce alignment with the same PE-score, which is the sum of the individual read alignment scores,

I thought along the same lines, but the alignment score is different for the second read (`AS:i:72` vs `AS:i:70`). Or would an identical joint score still be possible? Or there’s a bug in robin_hood ...

**Comment by ksahlin** [comment]
Oh I misread the cigar strings. But then the new version chooses an alignment that is worse than the best (given how the 'best' is defined) - as none of the alignment configurations are 'mapped in proper pair'. (of course the second one is better if inversion is more likely than translocation).

This could be an issue that comes back and haunts us.

**Comment by marcelm** [comment]
Merging #145 will close this, so I have created a new issue for the `robin_hood::unordered_map` problem that came up.

**Comment by ksahlin** [comment]
agreed to close
