### ISSUE TITLE
Picard ValidateSamFile: INVALID_ALIGNMENT_START

### ISSUE THREAD

**Issue by marcelm** [ksahlin/StrobeAlign#148]
Picard ValidateSamFile has many complaints like this:
```
ERROR::INVALID_ALIGNMENT_START:Record 23701, Read name SRR6055476.11851, Mate Alignment start (3496047) must be <= reference sequence length (44411) on reference NW_007931074.1
```

**Comment by ksahlin** [comment]
Well, the error message looks scary. Are we reporting alignments outside reference sequences? Or, more likely from the error message, is this inferred by Picard from an erroneous 'mate location' field?

**Comment by marcelm** [comment]
This seems to be about an unmapped read:
```
SRR6055476.11851  105  NT_033778.4     3496047 0   98=1X43=1X8=  NW_007931074.1  3496047  0  ... ...  NM:i:2  AS:i:282
SRR6055476.11851  149  NW_007931074.1  3496047 0   *             NT_033778.4     3496047  0  ... ...
```
(BTW, did you know you can run `samtools flags 149` to see that 149 means UNMAP,REVERSE,READ2?)

This indeed looks a bit weird in some ways.
- The unmapped read has a reference name associated with it. Is it on purpose, that is, does this carry any information that you would like to keep or might it just as well be set to `*`?
- The unmapped read has its position set to the same as the mapped one although they are on different contigs
- The REVERSE flag is set for the unmapped read. I guess one can do that, but my feeling is it shouldn’t be set and unmapped read should always be stored in their original orientation.
