### ISSUE TITLE
-r option

### ISSUE THREAD

**Issue by sjaenick** [ksahlin/StrobeAlign#19]
Hi @ksahlin,

for automated pipelines that employ strobealign, it's difficult to come up with a sensible setting
for the `-r` parameter (even though it has a default value) since datasets to be processed will likely
have different read lengths. Would it make sense to e.g. automatically infer a value here by 
looking at the first n reads to be mapped?

**Comment by ksahlin** [comment]
I agree and it should be easy. I will implement this.

**Comment by ksahlin** [comment]
Hi @sjaenick ,

I have just released v0.7, which removes the need to specify `-r`. The new release implements much more efficient multithreading impacting speed. Happy for any feedback.
