### ISSUE TITLE
Possibly switch from HyperLogLog to HyperLogLog++

### ISSUE THREAD

**Issue by marcelm** [ksahlin/strobealign#193]
We currently (as soon as #191 is merged) use the HyperLogLog algorithm (Flajolet et al, 2007) to estimate the number of unique randstrobe hashes.

There is an [improved variant of the algorithm](https://research.google.com/pubs/archive/40671.pdf) called HyperLogLog++ that gives even more accurate results and permits counting higher cardinalities. I’m not sure where the limit is in [the HyperLogLog implementation that we use](https://github.com/hideo55/cpp-HyperLogLog/), but if I understand the HyperLogLog++ paper correctly, using a 32-bit hash (which this implementation does) gives more inaccurate estimates the closer the cardinality gets to $2^{32}$.

The largest genome I’ve looked at is wheat (issue #192). It has 14 Gbp and gives us 1.3 billion distinct randstrobe hashes. The HyperLogLog estimate is 1.5 billion. We only need to get the order of magnitude right since the hash table size is always a power of two anyway, so it seems we are fine at the moment.

However, before looking at wheat, I had spent some time looking for C++ HyperLogLog++ implementations, and I want to at least document what I found.

* https://github.com/dialtr/libcount: Requires some work to get it integrated becauses it consists of relatively many files.
* https://github.com/omsitapara23/HyperLogLog-HIP: Should be easy to integrate because it consists of just a couple of header files. Only two weeks old at time of writing.
* https://github.com/arashbm/hyperloglog: also multiple files; author active quite recently

I’m fine with just closing this issue.

**Comment by ksahlin** [comment]
I see. Yes I am fine with closing this issue. And if it needs a revisit we have good information on where to look for an implementation here.
