### ISSUE TITLE
Suppress output of unaligned reads?

### ISSUE THREAD

**Issue by sjaenick** [ksahlin/strobealign#206]
Hi @ksahlin and @marcelm,

would you consider adding a command line option to suppress output for unaligned
reads, i.e. similar to bowtie2's `--no-unal`?

**Comment by marcelm** [comment]
That shouldn’t be too hard to add if @ksahlin thinks it’s worth to have this (you can of course always pipe into `samtools view -F 4`).

**Comment by ksahlin** [comment]
Sure, why not. If it can be implemented without introducing overhead (which I assume it can with pretty much an if-statement).

**Comment by sjaenick** [comment]
For some PE test data with many unmapped reads, this can speed up things to a certain extent:

strobealign -t 20 -N 5
real    1m47,766s
user    17m27,093s
sys     1m28,432s
~29G SAM output

strobealign -t 20 -N 5 -U
real    1m25,848s
user    16m54,221s
sys     0m39,950s
~5.9G SAM output

**Comment by marcelm** [comment]
Interesting that formatting these SAM records takes so much time. This reminds me that issue #63 is still open.
