### ISSUE TITLE
Follow recommended practice for SAM output

### ISSUE THREAD

**Issue by marcelm** [ksahlin/strobealign#212]
Section 2 in the [SAM specification](http://samtools.github.io/hts-specs/SAMv1.pdf) has a list of recommendations for SAM output. We should check the following ones:

- [x] The HD line should be present, with either the SO tag or the GO tag (but not both) specified.
- [ ] No alignments should be assigned mapping quality 255.
- [x] For a unmapped paired-end or mate-pair read whose mate is mapped, the unmapped read should
have RNAME and POS identical to its mate.
- [x] If all segments in a template are unmapped, their RNAME should be set as ‘*’ and POS as 0.
- [x] If POS plus the sum of lengths of M/=/X/D/N operations in CIGAR exceeds the length specified in the LN field of the SQ header line (if exists) with an SN equal to RNAME, the alignment should be unmapped, unless the reference sequence is circular (see below).
- [x] Unmapped reads should be stored in the orientation in which they came off the sequencing machine
and have their reverse flag bit (0x10) correspondingly unset.
- [x] SEQ and QUAL of secondary alignments should be set to ‘*’ to reduce the file size.
- [x] The NM tag should be present.

**Comment by valentynbez** [comment]
Consider interoperability with `samtools` and `pysam`, as they're the most popular libraries for parsing SAM files.
