### ISSUE TITLE
Enabling AVX2

### ISSUE THREAD

**Issue by marcelm** [ksahlin/strobealign#214]
Strobealign runs faster if AVX2 instructions are enabled (`-mavx2`), but not all CPUs support them. We need to deal with this somehow.

Some options:
1. Disable AVX2 by default, let people enable it if they want (status quo).
2. Enable AVX2 by default. People with too old machines need to compile their own binaries.
3. Distribute two binaries: one with AVX2 and one without.
4. Detect whether the CPU supports AVX2 at runtime and call different functions based on that.

I found [this discussion in the Blender forum](https://devtalk.blender.org/t/proposal-bump-minimum-cpu-requirements-for-blender/26855) quite interesting. The takeaways are:
* 90% of CPUs in the [Steam hardware survey](https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam?platform=combined) (click on "other settings" at the bottem) support AVX2
* 99% support SSE4.2
* When GCC compiles for x86-64, the default is to enable SSE2 (as that is available on all 64-bit x86 CPUs).
* There’s `-march=x86-64-v2` [(feature levels)](https://www.phoronix.com/news/GCC-11-x86-64-Feature-Levels), which enables SIMD extensions up to SSE4.2 and a couple of other things.

Based on the above, I played around with some settings and got these measurements (caveat: once again Drosophila):

Flags (in addition to `-O3`) | time |
-|-|
|(none)| 20.1 s|
`-march=skylake`| 19.8 s
`-march=x86-64-v2 -mtune=znver3`| 19.5 s
`-msse4.2`|19.4 s
`-mavx2`| 19.1 s|
`-march=x86-64-v3 -mtune=znver3`|19.1 s
`-march=znver2`| 19.1 s 
`-march=znver3`| 19.1 s
`-march=znver1`| 19.0 s
`-mavx2`, but only for `ssw.c` and `xxhash.c`| 19.0 s
`-march=native`| 18.9 s

I first set the flags using `-DCMAKE_CXX_FLAGS="-march=native"` etc., but this had almost no effect. Then I realized that this only sets the flags for C++ source files and that we have some C files as well. When I additionally used `-DCMAKE_C_FLAGS="-march=native"`, I saw a difference. And *not* setting the flag for C++ files did not make a discernible difference, so I assume that the benefits from using AVX2 are relevant only for the alignment module and the hash function (`ssw.c` and `xxhash.c`).

From the above, the minimum thing we could do is to enable `-msse4.2` by default as it gives already some benefit and is available on nearly all machines.

**Comment by ksahlin** [comment]
This is really useful information, thanks for the small writeup!

> I assume that the benefits from using AVX2 are relevant only for the alignment module and the hash function (ssw.c and xxhash.c).

Looking ahead, not that you suggested it, but I am not sure we should tailor optimizations to ssw.c and xxhash.c. 

Firstly, I was referred to [wyhash](https://github.com/wangyi-fudan/wyhash) by Rob Patro, and it seems significantly faster (~2.5x) than xxhash without observable loss in uniformity (see e.g., here https://github.com/ksahlin/strobemers/commit/2262b0bc0cd7ce6d3cae8a9825a5a955c950cb6b).  

Secondly,  I think WFA integration will be the single largest factor in reducing strobealign's runtime (https://github.com/ksahlin/strobealign/issues/26), which will make ssw obsolete. I am hopeful we could even see the align mode runtime go down close to mapping-only runtime. 

It is of course entirely possible that these libraries also enjoy speedup with the same flags.

> From the above, the minimum thing we could do is to enable -msse4.2 by default as it gives already some benefit and is available on nearly all machines.

I guess this is a good compromise. 

Based on preference, I would prefer testing the above-mentioned libraries (wyhash and primarily WFA) over time spent on, e.g., your option 4 (if it takes significant time). But I also know I have a move-fast-break-things approach too often when I shouldn't.

What do you think?

**Comment by marcelm** [comment]
> Firstly, I was referred to [wyhash](https://github.com/wangyi-fudan/wyhash) by Rob Patro, and it seems significantly faster (~2.5x) than xxhash without observable loss in uniformity (see e.g., here [ksahlin/strobemers@2262b0b](https://github.com/ksahlin/strobemers/commit/2262b0bc0cd7ce6d3cae8a9825a5a955c950cb6b)).

I’m not so sure this would speed things up TBH. I’ll open an issue about this.

> Secondly, I think WFA integration will be the single largest factor in reducing strobealign's runtime (#26), which will make ssw obsolete. I am hopeful we could even see the align mode runtime go down close to mapping-only runtime.

Yes, we need to reevaluate the CPU flags at that point.

> > From the above, the minimum thing we could do is to enable -msse4.2 by default as it gives already some benefit and is available on nearly all machines.
> 
> I guess this is a good compromise.
> 
> Based on preference, I would prefer testing the above-mentioned libraries (wyhash and primarily WFA) over time spent on, e.g., your option 4 (if it takes significant time). But I also know I have a move-fast-break-things approach too often when I shouldn't.
> 
> What do you think?

Let’s get a release out and then break things afterwards!

**Comment by ksahlin** [comment]
Right, you meant the compilation instructions for this release. 

Then I think perhaps  `-msse4.2` is a good solution based on your analysis above. But I will let you have the final say in this.

One thing I could mention is that  much more time is spent in extension alignment for biological ('real') libraries compared to simulated ones (see runtime plot here for BIO150 and BIO250 https://github.com/ksahlin/strobealign/issues/26#issuecomment-1241764108 compared to the others which are simulated). Meaning that SSW has a much higher influence in these scenarios. Is your drosophila testdata 'real' or simulated reads?

**Comment by marcelm** [comment]
> Right, you meant the compilation instructions for this release.
> 
> Then I think perhaps `-msse4.2` is a good solution based on your analysis above. But I will let you have the final say in this.

Here’s my suggestion now:
- In the compilation instructions, [we suggest that people use the `-march=native` flag](https://github.com/ksahlin/strobealign/blob/docs/README.md#from-source). This will enable whatever is available on the CPU the compiler is running on. Then we don’t need to tell people to enable AVX2 or AVX512, they just get it automatically if they compile from source. 
- For the Conda package, we use `-msse4.2`
- When/if you make pre-compiled binaries available, you need to decide whether you use `-mavx2` or `-msse4.2`.

> One thing I could mention is that much more time is spent in extension alignment for biological ('real') libraries compared to simulated ones (see runtime plot here for BIO150 and BIO250 [#26 (comment)](https://github.com/ksahlin/strobealign/issues/26#issuecomment-1241764108) compared to the others which are simulated). Meaning that SSW has a much higher influence in these scenarios.

That is interesting. I would have expected the simulated data to be closer to reality. Definitely something to keep in mind. Let’s discuss this when we add WFA2.

> Is your drosophila testdata 'real' or simulated reads?

Real reads from the Sequence Read Archive. I actually wanted to switch it to simulated data so that we can see the accuracy changes in CI, but now I’m not so sure. (Another issue I need to open ...)

**Comment by ksahlin** [comment]
> Here’s my suggestion now:

I like this suggestion. Let us go with it. 

For your third point, with the conda installation and the installation instructions that 'just works' (for me), I think there is little advantage of having precompiled binaries. Lets just remove them from the readme?

> I actually wanted to switch it to simulated data so that we can see the accuracy changes in CI, but now I’m not so sure. 

I think simulated data is the best we can do for accuracy, no? 

(unless we run e.g. WFA/SSW pairwise alignment for, say, 100k PE reads across eg the Drosophila genome and identify the 'real' best locations based on total edit/SW distance for the read pair, then use that set of reads with 'known locations'. That is is time consuming benchmark to set up though.)

**Comment by marcelm** [comment]
> > Here’s my suggestion now:
> 
> I like this suggestion. Let us go with it.
> 
> For your third point, with the conda installation and the installation instructions that 'just works' (for me), I think there is little advantage of having precompiled binaries. Lets just remove them from the readme?

Yes, I think that would be the best option.

> > I actually wanted to switch it to simulated data so that we can see the accuracy changes in CI, but now I’m not so sure.
> 
> I think simulated data is the best we can do for accuracy, no?
> 
> (unless we run e.g. WFA/SSW pairwise alignment for, say, 100k PE reads across eg the Drosophila genome and identify the 'real' best locations based on total edit/SW distance for the read pair, then use that set of reads with 'known locations'. That is is time consuming benchmark to set up though.)

Hm, that sounds quite time consuming indeed. Perhaps it’s easiest if we just continue testing on the real data that’s already there and simply add a simulated one. (I forgot to open that issue where we can discuss this ...)

**Comment by ksahlin** [comment]
Sounds good.

**Comment by marcelm** [comment]
Ok, closing this now because the instructions in the README have been updated.
