### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by marcelm** [ksahlin/strobealign#215]
Before:
- [x] Decide on a version number
- [x] Ensure changelog is up to date
- [x] Merge #208
- [x] Merge #211
- [x] Merge #213

During:
- [x] Update version number in changelog, commit, push
- [x] Wait until tests complete
- [x] Tag the version in Git (need to use `git tag -a`)
- [x] Compile and check that `strobealign --version` output is correct
- [x] `git push --tags`
- [x] :tada:

After:
- [x] Update Bioconda recipe
- [x] Announce

**Comment by ksahlin** [comment]
The plan looks good.

Regarding version number, is it not big enough to merit v0.8? (I know there are more strict guide lines for version numbering though).

**Comment by marcelm** [comment]
Definitely 0.8.0. A very popular versioning scheme is [semantic versioning](https://semver.org/), which requires bumping the minor version (the 7 in 0.7.1) when adding new features. Strictly speaking, SemVer also says that you don’t have to follow that rule as long as you are pre-1.0.0, but it’s nice to do it anyway.

SemVer also wants you to always use all three components of the version number, so it would be 0.8.0 instead of 0.8.

Of course you don’t have to use SemVer, and it is sometimes not obvious how to apply its rules, but I think it’s a good start.

(And as a note for the future: You could continue to use [0ver](https://0ver.org/), but I suggest you don’t ...)

**Comment by ksahlin** [comment]
I had a quick read through both SemVer and 0ver. Let us go with SemVar and version 0.8.0 for the upcoming release. I think I was trying to mimic SemVar versioning style earlier without knowing exactly what I was doing.

**Comment by marcelm** [comment]
(0ver is a joke, not sure if that was clear.)

**Comment by ksahlin** [comment]
Haha I skimmed 0ver and was like,, "why?!", but too occupied with teaching etc to invest more time understanding, so I did not catch the joke (facepalm)

**Comment by marcelm** [comment]
Everything is ready for the release. Shall I make one?

**Comment by ksahlin** [comment]
Let's do it! 💯

**Comment by marcelm** [comment]
[Done!](https://github.com/ksahlin/strobealign/releases/tag/v0.8.0)

I’ll take care of the Bioconda recipe soon.

**Comment by marcelm** [comment]
The [Bioconda recipe has been merged](https://github.com/bioconda/bioconda-recipes/pull/39124).

Do you want to tweet/toot this, or should we fix issue #222 first? Currently, the [files available for download from the release page](https://github.com/ksahlin/strobealign/releases/tag/v0.8.0) cannot be used to compile strobealign.

**Comment by ksahlin** [comment]
Nice!  I am okay with tweeting/tooting/advertising on mailing lists now that the bioconda version is updated. Will get back to you over email about the ad.
