### ISSUE TITLE
bam file header not compatible with GATK

### ISSUE THREAD

**Issue by danessel** [ksahlin/StrobeAlign#22]
Hi, using GATK as a variant caller raises an error about the sort order of the chromosomes and indeed they are not sorted although samtools sort was used. 
The header looks like this
```
@HD     VN:1.6  SO:coordinate
@SQ     SN:StSOLv1.1ch07_RagTag LN:51859799
@SQ     SN:StSOLv1.1ch01_RagTag LN:89994189
@SQ     SN:StSOLv1.1ch12_RagTag LN:108042198
@SQ     SN:Chr0_RagTag  LN:74722543
@SQ     SN:StSOLv1.1ch08_RagTag LN:122763581
@SQ     SN:StSOLv1.1ch02_RagTag LN:52958123
@SQ     SN:StSOLv1.1ch11_RagTag LN:82684344
@SQ     SN:StSOLv1.1ch09_RagTag LN:110327934
@SQ     SN:StSOLv1.1ch06_RagTag LN:77416214
@SQ     SN:StSOLv1.1ch04_RagTag LN:108266590
@SQ     SN:StSOLv1.1ch05_RagTag LN:91627361
@SQ     SN:StSOLv1.1ch10_RagTag LN:63742240
@SQ     SN:StSOLv1.1ch03_RagTag LN:45113244
@PG     ID:strobealign  PN:strobealign  VN:0.7  CL:strobealign
@PG     ID:samtools     PN:samtools     PP:strobealign  VN:1.13 CL:samtools fixmate -@5 -u -m - -
@PG     ID:samtools.1   PN:samtools     PP:samtools     VN:1.13 CL:samtools view -bhS -
@PG     ID:samtools.2   PN:samtools     PP:samtools.1   VN:1.13 CL:samtools sort -@5
@PG     ID:samtools.3   PN:samtools     PP:samtools.2   VN:1.13 CL:samtools view -H Altus.ColombaNRGene.ragtag.strobealign.bam
```

any ideas what is going wrong ? Other aligners like bwa produce a proper sorted bam file

**Comment by ksahlin** [comment]
Also, from reading the first line `@HD     VN:1.6  SO:coordinate` it seems the reads are ordered w.r.t. coordinate, but how should the chromosomes be sorted?

**Comment by danessel** [comment]
this is the header of the bwa aligned 
@HD     VN:1.6  SO:coordinate
@SQ     SN:StSOLv1.1ch01_RagTag LN:89994189
@SQ     SN:StSOLv1.1ch02_RagTag LN:52958123
@SQ     SN:StSOLv1.1ch03_RagTag LN:45113244
@SQ     SN:StSOLv1.1ch04_RagTag LN:108266590
@SQ     SN:StSOLv1.1ch05_RagTag LN:91627361
@SQ     SN:StSOLv1.1ch06_RagTag LN:77416214
@SQ     SN:StSOLv1.1ch07_RagTag LN:51859799
@SQ     SN:StSOLv1.1ch08_RagTag LN:122763581
@SQ     SN:StSOLv1.1ch09_RagTag LN:110327934
@SQ     SN:StSOLv1.1ch10_RagTag LN:63742240
@SQ     SN:StSOLv1.1ch11_RagTag LN:82684344
@SQ     SN:StSOLv1.1ch12_RagTag LN:108042198
@SQ     SN:Chr0_RagTag  LN:74722543

**Comment by ksahlin** [comment]
Okay, I see. The second suspect is the downstream commands.
```
@PG     ID:samtools     PN:samtools     PP:strobealign  VN:1.13 CL:samtools fixmate -@5 -u -m - -
@PG     ID:samtools.1   PN:samtools     PP:samtools     VN:1.13 CL:samtools view -bhS -
@PG     ID:samtools.2   PN:samtools     PP:samtools.1   VN:1.13 CL:samtools sort -@5
@PG     ID:samtools.3   PN:samtools     PP:samtools.2   VN:1.13 CL:samtools view -H Altus.ColombaNRGene.ragtag.strobealign.bam
```

Was bwa output produced with the same samtools commands (besides the fixmate call, which I assume is not needed for `bwa`)?

**Comment by danessel** [comment]
Without downstream commands the header looks like ..., which is the same after processing with samtools
So it seems that samtools is not able to sort the file for whatever reason, sam format correct ?
@SQ     SN:StSOLv1.1ch07_RagTag LN:51859799
@SQ     SN:StSOLv1.1ch01_RagTag LN:89994189
@SQ     SN:StSOLv1.1ch12_RagTag LN:108042198
@SQ     SN:Chr0_RagTag  LN:74722543
@SQ     SN:StSOLv1.1ch08_RagTag LN:122763581
@SQ     SN:StSOLv1.1ch02_RagTag LN:52958123
@SQ     SN:StSOLv1.1ch11_RagTag LN:82684344
@SQ     SN:StSOLv1.1ch09_RagTag LN:110327934
@SQ     SN:StSOLv1.1ch06_RagTag LN:77416214
@SQ     SN:StSOLv1.1ch04_RagTag LN:108266590
@SQ     SN:StSOLv1.1ch05_RagTag LN:91627361
@SQ     SN:StSOLv1.1ch10_RagTag LN:63742240
@SQ     SN:StSOLv1.1ch03_RagTag LN:45113244
@PG     ID:strobealign  PN:strobealign  VN:0.7  CL:strobealign

**Comment by ksahlin** [comment]
Does the original `bwa` header look the same as in strobealign, or is it already sorted?

If it is already sorted, I could sort it within strobealign.  I will add new release soon anyway. I'm not sure about the sorting though (lexicographic?), hence why I want to check what you obtain with bwa.

**Comment by danessel** [comment]
this is the header of bwa without post processing
@SQ     SN:StSOLv1.1ch01_RagTag LN:89994189
@SQ     SN:StSOLv1.1ch02_RagTag LN:52958123
@SQ     SN:StSOLv1.1ch03_RagTag LN:45113244
@SQ     SN:StSOLv1.1ch04_RagTag LN:108266590
@SQ     SN:StSOLv1.1ch05_RagTag LN:91627361
@SQ     SN:StSOLv1.1ch06_RagTag LN:77416214
@SQ     SN:StSOLv1.1ch07_RagTag LN:51859799
@SQ     SN:StSOLv1.1ch08_RagTag LN:122763581
@SQ     SN:StSOLv1.1ch09_RagTag LN:110327934
@SQ     SN:StSOLv1.1ch10_RagTag LN:63742240
@SQ     SN:StSOLv1.1ch11_RagTag LN:82684344
@SQ     SN:StSOLv1.1ch12_RagTag LN:108042198
@SQ     SN:Chr0_RagTag  LN:74722543
@RG     ID:Altus        SM:Altus

**Comment by ksahlin** [comment]
I have likely identified the issue: I have now implemented to guarantee that the header is output in the identical order as to how the chromosomes were found in the reference fasta. This was not the case before.

This most likely fixes the issue as you may supply GATK with the reference as will. 

I will update to release later today and then close this issue. Thanks for reporting!

**Comment by ksahlin** [comment]
Hi @danessel,

It took a bit longer because of testing, but the new release, v0.7.1, should fix this bug. Let me know how it goes.

**Comment by danessel** [comment]
Hi, yes thanks for the update, the files are now nicely processed by the varinatcallers I'm using

**Comment by ksahlin** [comment]
Great! If you are benchmarking the performance and would find some issues/abnormalities/negative results, please let me know. I have just received long-term support for Strobealign so that we can work on further improving and adding features such as reporting of supplementary read mappings.
