### ISSUE TITLE
Parallelize indexing

### ISSUE THREAD

**Issue by ksahlin** [ksahlin/strobealign#23]
Note to developer:
1. Separate indexing from alignment so that we can throw out 64-bit hash from flat vector when hash table is built - reduces memory during alignment a bit.
2. Indexing speed: Parallelize seed extraction over chromosomes.
(3. About 50% of the time is sorting the flat vector and building hash table though, faster sorting could be performed with radix sort as in minimap2.)

**Comment by marcelm** [comment]
Updates on this: All of this is done (or does not apply anymore) except for the parallel seed extraction.

**Comment by marcelm** [comment]
The last remaining item (parallel seed extraction) has been implemented in #307.
