### ISSUE TITLE
mapping Hi-C read

### ISSUE THREAD

**Issue by yangfangyuan0102** [ksahlin/strobealign#248]
Hi, Dear Author,
When I map the HiC reads, I use "bwa mem -SP5 genome read1 read2". I wonder if there is an equivalent options like “-SP5” ?

**Comment by ksahlin** [comment]
Hi @yangfangyuan0102 ,

Strobealign does not implement split (i.e., supplementary) alignments yet, which I think the option `-5` means in BWA-MEM, but it is on the roadmap (#13).

The other two options (`-SP`) should by default be enabled if you only map single-end reads, as your run command implies.

**Comment by yangfangyuan0102** [comment]
> Hi @yangfangyuan0102 ,
> 
> Strobealign does not yet support split (i.e., supplementary) alignments yet, which I think the option `-5` means in BWA-MEM. Split alignment support is however on the roadmap (#13).
> 
> The other two options (`-SP`) should by default be enabled if you only map single-end reads, as your run command implies.

Thanks, Looking forward to seeing this tools can be used for HIC alignment.
