### ISSUE TITLE
Some confusion of strobealign

### ISSUE THREAD

**Issue by AlAuAu** [ksahlin/strobealign#254]
It‘s a very good idea!!!But I still have some confusion of it.First,why do we finally choose the randstrobe as the method to construct the strobemers?How do the other two methods perform?Second,why we finally choose two strobes to construct a strobemer?Is there a rule to determine the number of strobes?

**Comment by ksahlin** [comment]
Hi @AlAuAu ,

Thank you!

1. Randstrobes provides better randomness and therfore better sequence matching (see details [in this paper](https://www.biorxiv.org/content/10.1101/2022.10.13.512198v2)). Also, they are roughly as fast to compute as hybridstrobes and minstrobes in C++.
2. I haven't tried the other methods. Just used an informed guess based on arguments in point 1 and the results in the original strobemers paper.
3.  No there is no rule yet. We are still in early stages on exploring strobemers both in theory and in applications. Some preliminary analysis sugest that strobemers beyond 3 offers little advantage (suppl data in [in this paper](https://www.biorxiv.org/content/10.1101/2022.10.13.512198v2)), But this analysis is just in respect to certain scenarios. For example, minstrobes of order 5 or 7(?) were used [in this paper](https://pubmed.ncbi.nlm.nih.gov/36685727/).

**Comment by AlAuAu** [comment]
> Hi @AlAuAu ,
> 
> Thank you!
> 
> 1. Randstrobes provides better randomness and therfore better sequence matching (see details [in this paper](https://www.biorxiv.org/content/10.1101/2022.10.13.512198v2)). Also, they are roughly as fast to compute as hybridstrobes and minstrobes in C++.
> 2. I haven't tried the other methods. Just used an informed guess based on arguments in point 1 and the results in the original strobemers paper.
> 3. No there is no rule yet. We are still in early stages on exploring strobemers both in theory and in applications. Some preliminary analysis sugest that strobemers beyond 3 offers little advantage (suppl data in [in this paper](https://www.biorxiv.org/content/10.1101/2022.10.13.512198v2)), But this analysis is just in respect to certain scenarios. For example, minstrobes of order 5 or 7(?) were used [in this paper](https://pubmed.ncbi.nlm.nih.gov/36685727/).

That help me a lot ！Thank you very much.
