### ISSUE TITLE
Release strobealign 0.9.0

### ISSUE THREAD

**Issue by marcelm** [ksahlin/strobealign#257]
* [x] Merge #256
* [x] Ensure changelog is up to date
* [x] Update version number in `CMakeLists.txt`
* [x] `git tag` the version
* [x] Push
* [x] Make a new release via the GitHub UI
* [x] In the Bioconda recipe, update tests to check for correct version number and remove the workaround for not being able to build from a release tarball.

**Comment by ksahlin** [comment]
Great, I'll wait for the bioconda recipe to be accepted before announcing
