### ISSUE TITLE
Consider reducing k for read length 50

### ISSUE THREAD

**Issue by marcelm** [ksahlin/strobealign#272]
We discussed this during our recent meeting: Reducing $k$ for read length 50 from the default of $k=20$ gives higher mapping rate and accuracy on the test datasets.

Here are the results for 2 x 50bp paired-end reads. ~~I will edit the table as soon as I have all results for rye.~~ Numbers added.

I don’t have good numbers for mapping times, yet. They appear to go up by <10%. I will get some numbers as soon as I have a quiet system.

## Mapping rate

Reference | $k = 20$ | $k=19$ | $k=18$ | $k=17$ |
-|-|-|-|-
drosophila | 99.46615| 99.56685| 99.64465 | **99.69955** |
CHM13      | 99.316  | 99.39755|99.4694|**99.51295**|
maize      |99.41475|**99.44605**|99.4441|99.4203|
rye  | **99.22915** |99.22355 | 99.22355 | 99.0205 | 

## Accuracy

Reference | $k = 20$ | $k=19$ | $k=18$ | $k=17$ |
-|-|-|-|-
drosophila |90.0774|90.1818|90.3049|**90.3616**|
CHM13      |90.4725|90.6161|90.69315|**90.786**
maize      |71.2683|71.54695|71.72395|**71.9865**
rye  |68.88975 |69.16655|69.37835 |**69.53555**

**Comment by ksahlin** [comment]
Just to double check: Accuracy is calculated as `#correct/total_reads`, and not `#correct/#mapped_reads`, right? (I guess you use a modified jaccard version of the script I used in the paper, In thet case it should be divided on total_reads)

Based on the accuracy and mapping rate, k=17 or 18 looks like interesting alternatives. Lowering k for canonical read length 50 will lower it for read lengths < 91 IIRC.

Is it easy to check the 2*75 nt reads as well? My intent is not to be annoying with extra analyses :) there is a reason behind it:  
 First, 75nt reads may be more common than 50nt(?). Second, as we know there is a tradeoff in k. With lower k we may find more 'non-destroyed' seeds (good). However, seeds also get more repetitive and we lose them to masking (bad; as hinted in the mapping rate table for the k=17 on rye genome).  For 50nt reads the good effect is obviously much more pronounced. However, with longer read length this good effect may not be as large.

**Comment by ksahlin** [comment]
Interesting. Not crystal clear what to do with this. Some suggestions:

- Leave as is to prioritise other tasks. (but it is a bit of a shame now that you have done most of the analysis to motivate a parameter change)
- Make a new canonical read length 75, by splitting ranges `r <= 65` (canonical 50), `65 < r <= 90` (canonical 75) and use k=17 for canonical 50 and k=20 for canonical 75.
- The result that you posted for 100nt is interesting since the optimum in accuracy appears to be at 'boundary' (k=20) in most cases. It immediately begs the question what happens at k=21.

**Comment by ksahlin** [comment]
Wow, those are very encouraging results. 

I would prefer creating a new canonical class. As you mentioned in one of the closed issues, index speed in not really a bottleneck for anything anymore and I don't see a big downside in having a worst case of one more index on disk for those who needs it. 

So, for two new canonical classes, wouldn't  https://github.com/ksahlin/strobealign/commit/b6d093e7f161badebc313e7d0d72326dbf99e764 be strictly better for 50bp reads? 

The I agree that doing another round of optimization for 75bp reads would be good.

**Comment by marcelm** [comment]
> I would prefer creating a new canonical class. As you mentioned in one of the closed issues, index speed in not really a bottleneck for anything anymore and I don't see a big downside in having a worst case of one more index on disk for those who needs it.

The only downside is that it’ll be a couple of hours work to do the new benchmarks ...

> So, for two new canonical classes, wouldn't [b6d093e](https://github.com/ksahlin/strobealign/commit/b6d093e7f161badebc313e7d0d72326dbf99e764) be strictly better for 50bp reads?

Yes, of course. I was juggling too many commit hashes.
