### ISSUE TITLE
CIGAR is not recognized by `samtools`

### ISSUE THREAD

**Issue by valentynbez** [ksahlin/StrobeAlign#289]
Hello,

I compiled the development version of `strobealign` with cmake. 
I run the command: 
```
strobealign/build/strobealign -U -R 4 -N 1000 -M 1000 -t 32 genomes_chunked/FENG15-1_1.fa.gz crc_phages.100mer.fa.gz 
> FENG15-1_1.strobealign.N1000.sam
```
The output looks as following:
```
FENG15-1_SAMEA3136768_METAG-scaffold_777_phage_45_virsorter_4500-4556   272     FENG15-1_SAMEA3136632_MAG_00000057-scaffold_3   1       255     54M3S   *       0  0AGCCAGTAATGGGTTAAGTGATAACAGGTGTCTGGAAATATAGGGGCAAATCCAGCA       *       NM:i:0  AS:i:118
```

But the CIGAR is not recognized by `samtools`:
```
[W::sam_parse1] mapped query must have a CIGAR; treated as unmapped
```

**Comment by valentynbez** [comment]
It would be a super useful feature for my project to have all alignments reported. Neither `bwa`, nor `bowtie2` nor `mmseqs2` are doing it.

**Comment by ksahlin** [comment]
Agreed, this is important.

**Comment by marcelm** [comment]
This regression was probably introduced in #235. I’ll look into this.

**Comment by marcelm** [comment]
I’ve opened a PR with a fix. (This was actually not introduced in #235.)

**Comment by ksahlin** [comment]
Thanks again @valentynbez, any feedback from your experiments are appreciated.
