### ISSUE TITLE
Do not count randstrobes

### ISSUE THREAD

**Issue by marcelm** [ksahlin/strobealign#304]
Instead estimate how many there are using the $\text{length}/(k-s+1)$ estimate

See https://github.com/ksahlin/strobealign/pull/278#issuecomment-1587238956

**Comment by ksahlin** [comment]
Sounds great. But if s-mers with XXhash are implemented (https://github.com/ksahlin/strobealign/issues/216#issuecomment-1592529027), maybe we should add back the small constant C? this is under the assumption that underestimating seeds is really bad as we need to reallocate a larger vector if so.

**Comment by marcelm** [comment]
Yes, I have that in mind. I also thought about adding a warning in case the estimate turns out to be too low (asking the user to report this to us). But of course with a large enough C that shouldn’t happen.

**Comment by ksahlin** [comment]
Not applicable anymore because we need exact counts because of parallell index creation.
