### ISSUE TITLE
Allow adding read group (RG) tags

### ISSUE THREAD

**Issue by marcelm** [ksahlin/strobealign#31]
It would be great if StrobeAlign could (optionally) add an `@RG` header and `RG` tags to each read. Having RG tags is a requirement in some of our pipelines and for some programs, and I would consider it best practice. It’s possible, but awkward to add read group tags afterwards with `samtools addreplacrg`.

For compatibility with BWA(-MEM)/minimap2, I would suggest to use command-line parameter `-R`, but at the moment, that is already used to set the "Rescue level". And although there would certainly be nicer ways to provide read group information than the way in which BWA does it, it would be good to at least also support the syntax that it uses (`-R '@RG\tID:foo\tSM:bar'`).

**Comment by ksahlin** [comment]
I agree that we should change to  use -R for read group and make the current -R (rescue level) to whatever letter not implemented in BWA (so to not have to change it again).
