### ISSUE TITLE
Running error with strobealign v0.7.1

### ISSUE THREAD

**Issue by psj1997** [ksahlin/strobealign#322]
Hi, 

I have tried to run strobealign with different versions in a benchmarking.

V0.8.0 and V0.9.0 works fine for me. 

But V0.7.1 leads to an error:  
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

I have tried installing from source and using the compiled file. 

Hope for your suggestions.

Sincerely
Shaojun

**Comment by marcelm** [comment]
`std::bad_alloc` is typically thrown when there is not enough RAM. Could that be it? There was some memory reduction in v0.8.0 compared to v0.7.1, see https://github.com/ksahlin/strobealign/pull/191#issuecomment-1379504994 for a table that shows how memory usage changed.

**Comment by psj1997** [comment]
OK. Thanks! It is a memory issue.
