### ISSUE TITLE
Strobealign gets killed when I try to run/index it

### ISSUE THREAD

**Issue by lajoycemboning** [ksahlin/strobealign#325]
Hello, recently I tried to run your software but when I try to create an index or directly run the command to map reads to a reference genome it gets killed before completion.

Can you help?

**Comment by ksahlin** [comment]
Hi @lajoycemboning.

We can help. But you have to provide some more information to do so. Can you please:

1. attach the error message you get
2. How much memory do you have? And what is the size of the reference you are mapping to?

**Comment by ksahlin** [comment]
Also please attach the command you ran strobealign with.

**Comment by lajoycemboning** [comment]
I was having memory issues so I was able to make it work:) Thanks for reaching out though
