### ISSUE TITLE
Illegal instruction ?

### ISSUE THREAD

**Issue by AntonioBaeza** [ksahlin/StrobeAlign#34]
strobealign StaphylococcusLT963435.fasta fastpSRR13329724_1.fastq.gz fastpSRR13329724_2.fastq.gz > outputStaphreads.sam
Using
k: 20
s: 16
w_min: 5
w_max: 11
Read length (r): 129
Maximum seed length: 79
Threads: 3
R: 2
Expected [w_min, w_max] in #syncmers: [5, 11]
Expected [w_min, w_max] in #nucleotides: [25, 55]
A: 2
B: 8
O: 12
E: 1
Time reading references: 0.01117 s

ref vector approximate size: 555450
Illegal instruction
(strobealign) ant@hillary:~/Turtle$

**Comment by ksahlin** [comment]
Hi @AntonioBaeza, 

is the data available somewhere public? And which OS did you use?

**Comment by marcelm** [comment]
StrobeAlign appears to be using a CPU instruction not available on your machine. Did you compile with `-march=skylake-avx512` as currently suggested in the README? AVX512 is not widely available, yet (no currently available AMD processors come with it, for example). If you did not add that option or you used the Bioconda package, then by default StrobeAlign targets AVX2, which should be available even on somewhat older CPUs.

If you are on Linux, you can check `/proc/cpuinfo` (or run `lscpu`) to see which of the AVX instruction sets you have.

There’s a possibility that the problem is a different one, please let us know at least how you installed StrobeAlign and which CPU you are on in that case.

**Comment by AntonioBaeza** [comment]
Thank you for your reply! I installed it from conda and I am using Linux Centos.

(base) ant@hillary:~$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       4
NUMA node(s):                    4
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           62
Model name:                      Intel(R) Xeon(R) CPU E5-4620 v2 @ 2.60GHz
Stepping:                        4
CPU MHz:                         2799.839
CPU max MHz:                     3000.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        5199.70
Virtualization:                  VT-x
L1d cache:                       1 MiB
L1i cache:                       1 MiB
L2 cache:                        8 MiB
L3 cache:                        80 MiB
NUMA node0 CPU(s):               0-7,32-39
NUMA node1 CPU(s):               8-15,40-47
NUMA node2 CPU(s):               16-23,48-55
NUMA node3 CPU(s):               24-31,56-63
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe sysc
                                 all nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulq
                                 dq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xs
                                 ave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erm
                                 s xsaveopt dtherm ida arat pln pts md_clear flush_l1d

**Comment by marcelm** [comment]
That particular CPU supports AVX, but not AVX2. I think we need to disable AVX2 support in the Conda recipe. I want to do some benchmarks first to see what the impact would be on runtime.

**Comment by AntonioBaeza** [comment]
great, thank you. I will install again from conda and test it!

**Comment by marcelm** [comment]
Someone needs to review and merge the updated recipe first, the updated version is not live, yet.

**Comment by marcelm** [comment]
The updated StrobeAlign package is now available.

**Comment by AntonioBaeza** [comment]
it is working now, thank you
