### ISSUE TITLE
Source compiled program runs much slower than the bioconda version

### ISSUE THREAD

**Issue by yanlifeng** [ksahlin/strobealign#373]
Hello, I'm having problems with the program compiled through the source code running much slower than the version installed by bioconda.

### **Running environment:**
AMD EPYC 7T83, 64 * 2 cores (supports AVX2 instruction set)
256G RAM
7T SSD
Rocky Linux release 8.8

### **Compile command:**
```bash:
cd strobealign
cmake -B build -DCMAKE_C_FLAGS="-march=native" -DCMAKE_CXX_FLAGS="-march=native"
make -j -C build
```

### **Run commands and results:**
**Source code compiled version:**
```bash:
time someGit/strobealign-0.11.0/build/strobealign /home/bigssd/ylf_data/Genome/GRCh38.d1.vd1.fa /home/bigssd/ylf_data/trim_pipeline/SRR7890824.trimmo_1P /home/bigssd/ylf_data/trim_pipeline/SRR7890824.trimmo_2P --use-index -t 128 > /dev/null
This is strobealign 0.11.0
Estimated read length: 149 bp
Time reading reference: 3.33 s
Reference size: 3107.58 Mbp (2779 contigs; largest: 248.96 Mbp)
Reading index from /home/bigssd/ylf_data/Genome/GRCh38.d1.vd1.fa.r150.sti
Total time reading index: 4.93 s
Running in paired-end mode
 Mapped      1136.08 M reads @     1.18 us/read
Done!
Total mapping sites tried: 2055485409
Total calls to ssw: 484903752
Calls to ksw (rescue mode): 230830253
Did not fit strobe start site: 19436304
Tried rescue: 95721168
Total time mapping: 1344.51 s.
Total time reading read-file(s): 6.50 s.
Total time creating strobemers: 37.13 s.
Total time finding NAMs (non-rescue mode): 112.99 s.
Total time finding NAMs (rescue mode): 111.12 s.
Total time sorting NAMs (candidate sites): 10.75 s.
Total time base level alignment (ssw): 1058.12 s.
Total time writing alignment to files: 0.00 s.
```
**Bioconda version:**
```bash:
time strobealign /home/bigssd/ylf_data/Genome/GRCh38.d1.vd1.fa /home/bigssd/ylf_data/trim_pipeline/SRR7890824.trimmo_1P /home/bigssd/ylf_data/trim_pipeline/SRR7890824.trimmo_2P --use-index -t 128 > /dev/null

This is strobealign 0.11.0
Estimated read length: 149 bp
Time reading reference: 3.78 s
Reference size: 3107.58 Mbp (2779 contigs; largest: 248.96 Mbp)
Reading index from /home/bigssd/ylf_data/Genome/GRCh38.d1.vd1.fa.r150.sti
Total time reading index: 4.81 s
Running in paired-end mode
 Mapped      1136.08 M reads @     0.56 us/read
Done!
Total mapping sites tried: 2055485409
Total calls to ssw: 484903752
Calls to ksw (rescue mode): 230830253
Did not fit strobe start site: 19436304
Tried rescue: 95721168
Total time mapping: 633.96 s.
Total time reading read-file(s): 56.27 s.
Total time creating strobemers: 35.53 s.
Total time finding NAMs (non-rescue mode): 113.13 s.
Total time finding NAMs (rescue mode): 109.85 s.
Total time sorting NAMs (candidate sites): 15.51 s.
Total time base level alignment (ssw): 294.79 s.
Total time writing alignment to files: 0.00 s.
```

We can see a lot of time difference in the ssw part, 1000s vs 300s. I did analyze it with intel's vtune tool, and it shows so much more time in the IO part in the source compiled version:
**Source compiled version:**
<img width="1012" alt="image-20231201111623066" src="https://github.com/ksahlin/strobealign/assets/18565391/d5bff9c6-c2fa-4c9c-a95d-5e39da17df92">
**Bioconda version:**
<img width="1023" alt="image-20231201111559733" src="https://github.com/ksahlin/strobealign/assets/18565391/5e2d0830-49da-4ad5-baec-7c5821d7e19a">

And I found that when the number of threads is relatively small (<12) the performance of both is about the same, only when the number of threads is higher (128) this problem occurs.
I also tried the latest version 0.12.0 and I have this problem too.
The strange thing is that I used the same test method on another intel server and the source compiled and bioconda version have almost the same runtime.

**Is there a difference between the bioconda release and the gituhub release? Or is there something wrong with the way I'm trying to compile.**

Thank you!

**Comment by marcelm** [comment]
Maybe the compiler version is different? According to [the logs](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=46387&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=4dddc55b-10bc-50fc-ac68-7ff899b7a030), the Bioconda version of strobealign was compiled with GCC 12.3.

Can you please check the output of the `cmake -B build ...` command? It should contain the compiler version.

The Bioconda recipe [uses these compilation flags](https://github.com/bioconda/bioconda-recipes/blob/74d19ff20bac32edac6ba09a12fe593f79fc5cdd/recipes/strobealign/build.sh):
```
    -DCMAKE_C_FLAGS="-msse4.2" \
    -DCMAKE_CXX_FLAGS="-msse4.2 -D_LIBCPP_DISABLE_AVAILABILITY" \
    -DCMAKE_C_STANDARD=11 \
    -DCMAKE_C_STANDARD_REQUIRED=ON
```
I would normally not expect `-march=native` to produce slower code, and the other options should not have an effect on speed.

**Comment by yanlifeng** [comment]
Thank you! That was such a quick reply.
It is indeed a gcc version issue, I use gcc12 and everything works fine.

By the way, are there any plans to use GPU to accelerate the ssw process?

**Comment by marcelm** [comment]
Great this helped!

Regarding the GPU version of SSW: This would be interesting, but is not currently planned as we neither have the experience nor hardware to do this. This would most likely happen if someone else steps up and sends in a pull request.
