### ISSUE TITLE
Using Strobealign for aligning RNAseq to recodonized gene

### ISSUE THREAD

**Issue by Rohit-Satyam** [ksahlin/strobealign#387]
Hi 

I have RNA-Seq data for a gene knockout produced by recodonization (see [here](https://academic.oup.com/bfg/article/18/5/281/5540241?login=true) for meaning because this is new to me). This gene has 4 exons but since the recodonization was done, therefore, it is hard to say which one falls where. I am in a bit of a situation where I have to make coverage maps to see if the knockout worked or not and since a major portion of the gene was recodonized (codons were changed), I thought of planning the RNA-Seq data directly to this recodonized sequence because altering the genome would be tricky for a gene. So I came across your paper and thought of using your aligner for this. Below is the result of a comparison of your aligner with minimap2 for this Illumina PE data with 150bp read length. 

![image](https://github.com/ksahlin/strobealign/assets/55479480/4ad4cf5c-5031-4c9d-8d29-012d3266c6cc)
 
I also tried to map the reads to the reference genome where the codons were not modified for this gene and tried to view the coverage for this gene in IGV and it looks like as follows:

![image](https://github.com/ksahlin/strobealign/assets/55479480/727b4e3d-78f7-4eb4-a90c-38d8e409d5b8)

I was told that this isn't the right approach since the recodonization will make RNA with different sequences (but will translate to the same protein sequence) and therefore will fail to map to the reference genomic region.

**Comment by marcelm** [comment]
Hi, I’m probably missing some context since this recodonization is also new to me, but can you clarify what your question is?

It seems that strobealign doesn’t give you coverage of the first two exons in contrast to minimap2, is that the observation you wanted to share? Strobealign has some limitations at the moment when mapping very short sequences, maybe that is the issue here.
