### ISSUE TITLE
Fasta accession modification

### ISSUE THREAD

**Issue by ksahlin** [ksahlin/StrobeAlign#4]
From issue #3:
 
"Small suggestion: remove the fasta annotation (only keep after > and before the first tab) from reference in sam output so that the sam output can be a little bit smaller. Or add an option to only keep them or an option to include annotation."

**Comment by jianshu93** [comment]
Hello Kristoffer,

This will be a very important feature for microbiology studies. Reads mapping is not only for human genome et.al., but also for microbial genome (bacterial genome, archaea genome). There are many species genomes in a spoon of water or soil, so mapping reads to the assembled genomes will be a little bit different, we use a competitive mapping strategy (pooling all genomes of all species, a read can map to multiple genomes/species, but the one with the highest identity will be used), so each record in the pooled fasta file (many species genomes) will need a identifier unique to the genome species where it comes from and we need to extract all the records related to this unique identifier in the final sam file to represent reads mapped to each species genomes. So the fasta annotation included will mess up everything (we can remove them before mapping for sure, but most peoples just ignore it) and a lot of the annotation are long, sam files will be larger. It would be really nice if you could ignore the annotation by default and add an option to allow including annotation.


Many Thanks,

Jianshu

**Comment by ksahlin** [comment]
I will have another development go very soon. will fix it then.

just a check, let's say the original reference is `>ref1 sample=blabla, other_info=blabla`. 

current output in strobealign is`ref1 sample=blabla, other_info=blabla`

you want `ref1` ?

**Comment by jianshu93** [comment]
just other info. no need to add sample. the identifier is unique to each sample，meaning include other info after the thist tab or not. default is not. check sam file SQ lines from bwa and bowtie2 with references have other info

Jianshu.

**Comment by ksahlin** [comment]
Hi Jianshu, I fixed this in the new release of v0.1. 

The new version (v0.1) also comes with major improvements that you should be able to see given the rata you had which consisted of reads of length 50-150nt from what I remember.
