### ISSUE TITLE
Question about columns in PAF output

### ISSUE THREAD

**Issue by W-L** [ksahlin/strobealign#432]
Hi devs! 
I just have a few quick questions to check my understanding of the paf output when using `-x`. Given the paf columns: 

```
1 query name
2 query length
3 query start
4 query end
5 relative strand
6 target name
7 target length
8 target start
9 target end
10 number of residue matches
11 alignment block length
12 mapping quality
 ```

1) the values in columns 3, 4, 8, and 9 will be approximate (as in minimap's output)?
2) col 11 = col 9 - col 8?
3) is col 10 the number of strobemer seed matches to the reference, instead of residues? (seems to always be <20 for a set of reads of 101nt that I tested on)

Thank you very much!

**Comment by ksahlin** [comment]
Hi @W-L,

Yes, you are correct in all three points!
