### ISSUE TITLE
command line syntax

### ISSUE THREAD

**Issue by jtamames** [ksahlin/strobealign#442]
Hello
This is likely a silly question, but I am having problems with the command to run the program as you put it:

`strobealign -t 60 01.H1.fasta H1.current_1.gz H1.current_2.gz | samtools sort -o sorted.bam
`
the result is:

`Usage:   samtools sort [options] <in.bam> <out.prefix>
`
Could you help me to fix the syntax?
Thanks a lot!
Best,
J

**Comment by marcelm** [comment]
You’re probably using a (very) old `samtools` version. I strongly recommend that you update, but in the meantime, I think you need to use both `samtools view` and `samtools sort` like this:
```
strobealign -t 60 01.H1.fasta H1.current_1.gz H1.current_2.gz | samtools view -Sb - | samtools sort -f - sorted.bam
```
Note that the current release of strobealign will likely not be able to use all 60 provided threads; this has only recently been fixed in the development version.

**Comment by jtamames** [comment]
Thanks for the answer! I thougth it was using the samtools in your conda distro, but it is using the one in my system instead, that probably is rather old, indeed.
Best,
J

**Comment by marcelm** [comment]
Good point. Samtools isn’t listed as a dependency of the `strobealign` Conda package, so just running `conda install strobealign` will not install it. I’ll update the installation instructions.

**Comment by marcelm** [comment]
Note to whoever stumbles over this issue: I just noticed the command I suggested above won’t work. It’s better to upgrade.

**Comment by jtamames** [comment]
Thank you Marcel.
Regarding this:

> Note that the current release of strobealign will likely not be able to use all 60 provided threads; this has only recently been fixed in the development version.

which is the actual limit of threads that strobealign can manage?
Best,
J

**Comment by marcelm** [comment]
Quoting from the [changelog](https://github.com/ksahlin/strobealign/blob/main/CHANGES.md#development-version) of the unreleased version:

> #269, #418: Strobealign scales now much better to systems with many cores. Previously, decompressing gzipped-compressed input files was a bottleneck starting at about 30 threads. We now use [ISA-L](https://github.com/intel/isa-l/) for decompression, which is about three times as fast as zlib, and decompression is also done in a separate thread. We tested up to 128 cores, and strobealign was still able to use all cores. Contributed by @telmin.

@ksahlin What do you think about making a new release?

**Comment by ksahlin** [comment]
A new release sounds good. Thanks Marcel!
