### ISSUE TITLE
Too many reference sequences

### ISSUE THREAD

**Issue by yangzuokun** [ksahlin/strobealign#454]
This is strobealign 0.13.0-25-g3a97f6b-dirty
Time reading reference: 163.97 s
Reference size: 94366.30 Mbp (23452997 contigs; largest: 8.40 Mbp)
strobealign: Too many reference sequences. Current maximum is 8388607

**Comment by ksahlin** [comment]
@marcelm at what point did we reduce the nr of references? Is it that the 1 extra bit for MCS already got integrated in main in this version?  Previously we had `2^24=16M`. 

We should move the 8 offset bits to the hash value to allow 2^32 refs. Either we could put them in the unused top N bits of the hash, or we could put them in the lowest bit to allow later for distinguishing seeds with different lengths.

Copy of discussion in https://github.com/ksahlin/strobealign/issues/421

**Comment by marcelm** [comment]
@yangzuokun Did you modify your copy of strobealign? When I use the same commit of strobealign as yours on an artificial reference with as many contigs as yours, I get:
```
This is strobealign 0.13.0-25-g3a97f6b
Time reading reference: 18.91 s
Reference size: 93.81 Mbp (23452997 contigs; largest: 0.00 Mbp)
strobealign: Too many reference sequences. Current maximum is 16777215
```
In strobealign 0.13.0, the maximum number of contigs is still $2^{24}-1$.

> @marcelm at what point did we reduce the nr of references? Is it that the 1 extra bit for MCS already got integrated in main in this version?

Yes, that’s already in main and also in strobealign 0.14.0. So the maximum number of references is now $2^{23}-1$.

@yangzuokun I’ll close this soon; please follow the discussion in #421 instead.
