### ISSUE TITLE
Some reads get MAPQ = 0 in the phiX test dataset

### ISSUE THREAD

**Issue by marcelm** [ksahlin/strobealign#52]
I opened the tiny test dataset (with phiX) alignments in IGV (top in screenshot) and compared it to what BWA-MEM outputs (bottom). Many of the phiX reads are mapped with a mapping quality of zero (these are the alignments in a lighter gray), but BWA-MEM assigns them a nonzero mapping quality.

![mapq0](https://user-images.githubusercontent.com/724864/188870903-54d4ecb9-96b5-4ff9-b9b6-38a3e7aaef25.png)

Read SRR1377138.40 is an example.

**Comment by ksahlin** [comment]
Interesting, cannot say why that is. But great example to start looking into whether the MAPQ values can be better.

**Comment by marcelm** [comment]
I’m going to close this because no normal reads in the phiX test dataset get a MAPQ of zero anymore, in particular not SRR1377138.40.

There is still a problem with reads unexpectedly getting MAPQ=0, but it is covered by #334.
