### ISSUE TITLE
Strategies for mutltimapping reads

### ISSUE THREAD

**Issue by sebgra** [ksahlin/StrobeAlign#8]
Hello,

first of all thanks for this efficient software. I was wondering if there is currently any option to retain all the reads with asociated flags on .sam output file, especially the FLAG tag specifying if the read is mapped 0, 1 or >1 time. This behavior is the same like -a option of Bowtie2. 

Multimapping reads seems to be discadreded at the time am I right ?

Thanks in advance

**Comment by ksahlin** [comment]
Hi @sebgra,

Yes at the time, but secondary alignments (of multimapping reads) are easy to implement given the current code. I will leave this issue open until I have implemented it.

Then there are supplementary alignments (parts of the read map to different locations) which I may consider implementing too but is slightly more complex.

Best,
Kristoffer

**Comment by ksahlin** [comment]
I should clarify just in case; multimapping reads are not currently discarded.

If a read maps to multiple locations, only the best one is reported. If there are several identical matches (either perfect match or the same SNVs/indels) then one of them will be reported.

**Comment by sebgra** [comment]
Hello ! 

That is what I meant by "discarded". I was wondering if there was any option to report all the positions possible for a read, with it's corresponding tags (MAPQ, CIGAR, etc.) 

Hope it would come later :)

**Comment by ksahlin** [comment]
I am implementing this at the moment. 

When you write "especially the FLAG tag specifying if the read is mapped 0, 1 or >1 time" do you mean the SAM flag field to specify if it is the primary alignment or a secondary alignment (i.e. setting 9th bit to 1 in the flag)?

If not, I'm assuming you mean one of the optional fields. Could you in this case point me to the right tag?

**Comment by sebgra** [comment]
Hi! 

Thanks for your interest in my multimapping case.

I'm currently using Bowti2 to align with the -a mode which reports all possible alignments. The documentation says : 

_Alignments are reported in descending order by alignment score. The alignment score for a paired-end alignment equals the sum of the alignment scores of the individual mates. Each reported read or pair alignment beyond the first has the SAM 'secondary' bit (which equals 256) set in its FLAGS field. Supplementary alignments will be assigned a MAPQ of 255._

[http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#a-mode-search-for-and-report-all-alignments](url)

Concerning the FLAG tag, I made a mistake, I'm also using it to filter events such as dangling ends, self-circle and such molecular biology stuff. This flag is reported as int like 16, 255 etc. 

It would be interesting in my case to have output .sam with such options, like the one that I can find in Bowtie2 output. 

Thanks in advance!

**Comment by ksahlin** [comment]
Hi @sebgra,

I have now released v0.5 which adds the option to output at most `-N` secondary alignments (upper bounded by `-M` (maximum mapping sites to try). The supplementary flag is set for the secondary alignments.

I will close this issue.  Please feel free to open another issue if there are additional tags you are missing for your analysis.

Happy for any feedback.

Best.
K
