### ISSUE TITLE
Structure of `index.cpp`

### ISSUE THREAD

**Issue by marcelm** [ksahlin/StrobeAlign#83]
I keep forgetting which functions call which other ones, so I (manually) made a call graph for the functions in `index.cpp`.

```mermaid
graph TD;
    main.cpp-->StrobemerIndex::populate;
    StrobemerIndex::populate --> generate_seeds;
    StrobemerIndex::populate --> count_unique_elements;
    StrobemerIndex::populate --> index_vector;
    generate_seeds --> seq_to_randstrobes2;
    generate_seeds --> std::sort;
    seq_to_randstrobes2 --> make_string_to_hashvalues_open_syncmers_canonical;
    seq_to_randstrobes2 --> get_next_strobe_dist_constraint;
    make_string_to_hashvalues_open_syncmers_canonical --> XXH64;
    make_string_to_hashvalues_open_syncmers_canonical --> update_window;
```
The above accounts for all functions in `index.cpp` except `seq_to_randstrobes2_read`.

I’m opening this mainly so that I have a place where I can put this flowchart, but one suggestion is to move `seq_to_randstrobes2` (and the `_read` variant) and everything below it to a separate file because that is the part that is also needed in `aln.cpp`. That is, split index creation from randstrobe generation.

**Comment by ksahlin** [comment]
This refactoring sounds good to me.
