### ISSUE TITLE
Structure of aln.cpp

### ISSUE THREAD

**Issue by marcelm** [ksahlin/strobealign#98]
This shows which functions call which in `aln.cpp`.

## All functions

Just for completeness, but this is a bit big.

```mermaid
graph LR;
    aln.cpp  --> align_SE_read;
    aln.cpp --> align_PE_read;

    align_SE_read --> seq_to_randstrobes2_read;
    align_SE_read --> find_nams;
    align_SE_read --> find_nams_rescue;
    align_SE_read --> output_hits_paf;
    align_SE_read --> align_SE/align_SE_secondary_hits;

    align_PE_read --> seq_to_randstrobes2_read;
    align_PE_read --> find_nams;
    align_PE_read --> find_nams_rescue;
    align_PE_read --> get_best_map_location;
    align_PE_read --> output_hits_paf_PE;
    align_PE_read --> align_PE;

    get_best_map_location --> get_best_scoring_NAM_locations;
    get_best_map_location --> i_dist_est::update;

    align_PE --> rescue_read;
    align_PE --> get_alignment;
    align_PE --> get_MAPQ;
    align_PE --> i_dist_est::update;
    align_PE --> get_best_scoring_NAM_locations;
    align_PE --> rescue_mate;
    align_PE --> joint_mapq_from_alignment_scores;
    
    rescue_read --> get_alignment;
    rescue_read --> rescue_mate;
    rescue_read --> get_best_scoring_pair;
    rescue_read --> joint_mapq_from_alignment_scores;

    rescue_mate --> ssw_align;

    get_alignment --> HammingToCigarEQX2;
    get_alignment --> align_segment;

    align_segment --> HammingDistance;
    align_segment --> ssw_align;

    align_SE/align_SE_secondary_hits --> HammingDistance;
    align_SE/align_SE_secondary_hits --> HammingToCigarEQX2;
    align_SE/align_SE_secondary_hits  --> ssw_align;
```

## Only functions in the single-end path

```mermaid
graph LR;
    align_SE_read --> seq_to_randstrobes2_read;
    align_SE_read --> find_nams;
    align_SE_read --> find_nams_rescue;
    align_SE_read --> output_hits_paf;
    align_SE_read --> align_SE/align_SE_secondary_hits;

    align_SE/align_SE_secondary_hits --> HammingDistance;
    align_SE/align_SE_secondary_hits --> HammingToCigarEQX2;
    align_SE/align_SE_secondary_hits --> ssw_align;
```

## Only functions in the paired-end path

```mermaid
graph LR;
    align_PE_read --> seq_to_randstrobes2_read;
    align_PE_read --> find_nams;
    align_PE_read --> find_nams_rescue;
    align_PE_read --> get_best_map_location;
    align_PE_read --> output_hits_paf_PE;
    align_PE_read --> align_PE;

    get_best_map_location --> get_best_scoring_NAM_locations;
    get_best_map_location --> i_dist_est::update;

    align_PE --> rescue_read;
    align_PE --> get_alignment;
    align_PE --> get_MAPQ;
    align_PE --> i_dist_est::update;
    align_PE --> get_best_scoring_NAM_locations;
    align_PE --> rescue_mate;
    align_PE --> joint_mapq_from_alignment_scores;
    
    rescue_read --> get_alignment;
    rescue_read --> rescue_mate;
    rescue_read --> get_best_scoring_pair;
    rescue_read --> joint_mapq_from_alignment_scores;

    rescue_mate --> ssw_align;

    get_alignment --> HammingToCigarEQX2;
    get_alignment --> align_segment;

    align_segment --> HammingDistance;
    align_segment --> ssw_align;
```

## To Do

* [x] `get_alignment` handles a single read, but is not used for single-end reads
* [x] Why do both `get_best_map_location` and `align_PE` call `i_dist_est::update`?

**Comment by ksahlin** [comment]
Those are good questions. 

1. I recall having implemented the `align_SE()` and it worked well. The `get_alignment` came much later in development when I tried to structure up paired end alignment. It is possible that `align_SE` could make use of `get_alignment`. From what I see now and can remember, `get_alignment` focus on a read alignment given one seed location, while `align_SE` does more. `align_SE`  finds the best alignment location by iterating over all seed locations and need much more variable initialisations like best score seen so far etc.
2. My guess is that we want to estimate inser size regardless of if we are in mapping mode (paf) or full alignment mode (sam). This estimation has the potential to be more accurate for aligned reads where we can filter true read pair mappings better. `get_best_map_location` will (probably) call `i_dist_est` if we are in mapping mode. If we are in alignment mode we will call this function after extension alignment to be sure we are using a high quality alignment.

**Comment by ksahlin** [comment]
Nice visualisations btw! I need to make use of those too.

**Comment by marcelm** [comment]
The diagrams are now quite outdated, the question about the `i_dist_est::update` has been answered and the to do item regarding `get_alignment` has been done, so I think it’s time to close this issue.
